#title: AVERtek # your name photo (or website title) here
logo1: "/images/Company Here.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <b>ON MOBILE DEVICE
  <br>View in Augmented Reality (AR):</b>
  <br><br>
    <b><u>STEP 1</u></b>- Scroll down press AR button; place image on flat surface; scale model
  <br><br>
  <a href="https://avertek.net/xr-now-health-care"><b><u>STEP 2</u></b>- View Detailed Anatomy</a> 
  <br><br>
  <a href="https://avertek.net/narrative"><b><u>STEP 3</u></b>- Review Video Instruction</a>
  <br><br>
  <a href="https://avertek.net/contact-us"><b><u>STEP 4</u></b>- Personal Consultation; Benefits</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
